### ISSUE TITLE
HttpClient 不需要设置超时时间吗 线程会hang

### ISSUE THREAD

**Issue by xueshun** [sensorsdata/sa-sdk-java#17]
https://github.com/sensorsdata/sa-sdk-java/blob/f2b3bbeff71e9df0e79e094548873ae1757fcb7c/SensorsAnalyticsSDK/src/main/java/com/sensorsdata/analytics/javasdk/consumer/HttpConsumer.java#L40

**Comment by fzyouni** [comment]
已经在 3.2.1 版本增加网络超时设置参数，修复该问题
