### ISSUE TITLE
数据上传失败没有返回报错内容

### ISSUE THREAD

**Issue by xueguanlu** [sensorsdata/sa-sdk-java#20]
FastBatchConsumer 的FailedData 中是否可以考虑增加报错信息，
比如 https://github.com/sensorsdata/sa-sdk-java/blob/master/SensorsAnalyticsSDK/src/main/java/com/sensorsdata/analytics/javasdk/consumer/FastBatchConsumer.java#L114

**Comment by fzyouni** [comment]
这个问题，我们已经注意到，并且在下一个版本更新中，在发送异常回调返回时，优化了返回信息

**Comment by fzyouni** [comment]
已经在 3.4.0 版本进行了优化
