### ISSUE TITLE
SDK does not support custom HTTP configurations

### ISSUE THREAD

**Issue by jdcaperon** [sensorsdata/sa-sdk-java#24]
Please add support for custom HTTP configurations, this can be done simply by letting users inject their own HTTP client or by making the client respect system properties. Currently, it is impossible with this SDK to support a proxy for requests. Currently we support forked and modified version of this SDK here: https://github.com/Canva/sa-sdk-java

* https://github.com/sensorsdata/sa-sdk-java/pull/11
* https://github.com/sensorsdata/sa-sdk-java/pull/12

Failing to add this kind of support is a security risk for your SDK and does not make it conducive to supporting real world clients.

**Comment by adamyaoqinglin** [comment]
@jdcaperon The #11 is too old to review. Could you please post a new pull request? 
Not only HttpConsumer should use HttpClient as constructor input, but also BatchConsumer and FastBatchConsumer and DebugConsumer。Also, the constructor should be a new one

**Comment by jdcaperon** [comment]
@adamyaoqinglin see https://github.com/sensorsdata/sa-sdk-java/pull/25
