### ISSUE TITLE
使用文档打不开：你选择的产品版本不包含此功能，故没有对应说明

### ISSUE THREAD

**Issue by BugCui** [sensorsdata/sa-sdk-java#26]
http://www.sensorsdata.cn/manual/java_sdk.html
使用文档打不开：你选择的产品版本不包含此功能，故没有对应说明
<img width="699" alt="image" src="https://user-images.githubusercontent.com/48312085/197949881-b7c8e55a-62c4-43cd-be72-f1cb7ad4b044.png">

**Comment by dengshiwei** [comment]
@BugCui 新文档链接：https://manual.sensorsdata.cn/sa/latest/java-sdk-1573929.html
