### ISSUE TITLE
buffer超过大小

### ISSUE THREAD

**Issue by kiwi-field** [sensorsdata/sa-sdk-java#27]
使用FastBatchConsumer类，1s钟放入10000个元素，还没有自动flush，调用send方法会返回can't offer to buffer

**Comment by liuweiqiang2016** [comment]
FastBatchConsumer 的 maxCacheSize，内存缓存队列保存记录最大条数，默认 6000，上限 10000，下限 1000，超过 10000 后将无法继续进入缓存。不建议一次塞入过多数据，会导致占用过多内存。如果有大量数据的需求，建议使用 ConcurrentLoggingConsumer，先保存在本地日志中，再使用 LogAgent 上报数据到后台。
详见：https://manual.sensorsdata.cn/sa/latest/tech_sdk_server_java_install-111903566.html#id-%E9%9B%86%E6%88%90%E6%96%87%E6%A1%A3%EF%BC%88Java%EF%BC%89-FastBatchConsumer
