### ISSUE TITLE
测试了一下，写windows路径没有输出日志

### ISSUE THREAD

**Issue by migthtsoft** [sensorsdata/sa-sdk-java#5]
测试了一下，写windows路径没有输出日志

**Comment by migthtsoft** [comment]
HelloSensorsAnalytics类中修改如下：
final SensorsAnalytics sa = new SensorsAnalytics(
                new SensorsAnalytics.ConcurrentLoggingConsumer("D:/data/logs/access_log"));

**Comment by fengjiajie** [comment]
指定这个路径需要 D:/data/logs/ 目录已经存在。使用当前最新版没有复现问题。
如果仍有问题，可以向神策技术支持同学提问。
