### ISSUE TITLE
在哪里设置数据接收地址？

### ISSUE THREAD

**Issue by wong2** [sensorsdata/sa-sdk-java#6]
文档中只提到了如何获取数据接收地址（在“获取配置信息”这一节），下面写到生产环境推荐使用 `ConcurrentLoggingConsumer`，但没有说明如何为它配置数据接收地址

**Comment by wong2** [comment]
是要配合 LogAgent 使用

**Comment by renqingyou** [comment]
你好，可以看下文档的 Java SDK 第 7 章，ConcurrentLoggingConsumer 是将数据缓存到本地磁盘中，然后 LogAgent 工具负责读取磁盘中的文件并上报，LogAgent 里面需要配置数据接收地址。
